name: Windows

on:
  push:
    branches:
      - main
    paths:
      - '/R3nzSkin/**'  # 限制只有在 R3nzSkin 目录及其子目录下的文件发生变化时才触发工作流程
  pull_request:
    types: [opened, synchronize, reopened, closed, pull_request_target]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        configuration: [ChinaServer]
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      if: contains(github.event.head_commit.message, '[ci skip]') == false
      shell: cmd
      run: msbuild R3nzSkin/R3nzSkin.vcxproj /p:Platform=x64 /p:Configuration=${{ matrix.configuration }}
    - name: Upload File
      if: contains(github.event.head_commit.message, '[ci skip]') == false
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: D:\a\R3nzSkin\R3nzSkin\R3nzSkin\Release\ChinaServer\R3nzSkin.dll

  # 其他任务...
